services:
  video-detection:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./static:/app/static
    environment:
      - FLASK_APP=app_Service.py
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped